// Banque de questions - Mode Vrai ou Faux
// Chaque question : { id, region, statement, correct(true/false), explanation }
const VF_QUESTIONS = [
{id:'vf-001', region:'Zaun', statement:"Jinx et Vi sont sœurs.", correct:true, explanation:"Vi et Jinx (autrefois surnommée Powder) ont grandi ensemble dans les bas-fonds de Zaun."},
{id:'vf-002', region:'Demacia', statement:"Demacia encourage activement l'usage de la magie chez ses citoyens.", correct:false, explanation:"Demacia se méfie profondément de la magie et la considère comme une menace à contrôler, voire à interdire."},
{id:'vf-003', region:'Bilgewater', statement:"Bilgewater est une théocratie dirigée par des prêtres pacifistes.", correct:false, explanation:"Bilgewater est un repaire de pirates et de chasseurs de primes, sans autorité centrale pacifique."},
{id:'vf-004', region:'Freljord', statement:"Le Freljord est une région tropicale et chaude.", correct:false, explanation:"Le Freljord est au contraire une terre glaciale, balayée par le froid et la neige."},
{id:'vf-005', region:'Freljord', statement:"Ornn est un dieu-forgeron associé au Freljord.", correct:true, explanation:"Ornn façonne le métal et les montagnes depuis les entrailles du Freljord."},
{id:'vf-006', region:'Zaun / Piltover', statement:"Zaun se trouve littéralement sous Piltover.", correct:true, explanation:"Zaun est une cité souterraine construite sous les fondations de Piltover."},
{id:'vf-007', region:'Ionia', statement:"Ionia entretient un lien spirituel fort avec la nature.", correct:true, explanation:"La culture ionienne est profondément liée aux esprits de la nature et à la magie ambiante."},
{id:'vf-008', region:'Noxus', statement:"Noxus interdit à quiconque n'étant pas noble de naissance d'accéder au pouvoir.", correct:false, explanation:"Au contraire, Noxus valorise la force et le mérite : même un esclave peut s'élever au sommet."},
{id:'vf-009', region:'Targon', statement:"Le Mont Targon permet à des mortels de devenir des Aspects.", correct:true, explanation:"Gravir Targon peut transformer un mortel en porteur d'un pouvoir céleste, un Aspect."},
{id:'vf-010', region:'Le Néant', statement:"Le Néant est une force bienveillante qui protège Runeterra.", correct:false, explanation:"Le Néant est au contraire une puissance destructrice qui dévore et corrompt tout ce qu'elle touche."},
{id:'vf-011', region:'Bandle City', statement:"Les yordles viennent de Bandle City.", correct:true, explanation:"Bandle City est le foyer mystérieux des yordles."},
{id:'vf-012', region:'Shurima', statement:"Shurima est un empire situé dans une région désertique.", correct:true, explanation:"Shurima s'étend sur de vastes étendues désertiques du sud de Runeterra."},
{id:'vf-013', region:'Shurima', statement:"Azir fut autrefois empereur de Shurima.", correct:true, explanation:"Azir régnait sur l'antique Shurima avant sa chute, et fut plus tard ressuscité."},
{id:'vf-014', region:'Noxus', statement:"Katarina appartient à une lignée de forgerons pacifistes.", correct:false, explanation:"Les Du Couteau, famille de Katarina, sont une lignée d'assassins redoutés à Noxus."},
{id:'vf-015', region:'Piltover', statement:"Camille travaille pour la maison Kiramman à Piltover.", correct:true, explanation:"Camille protège les intérêts de la maison Kiramman, une famille influente de Piltover."},
{id:'vf-016', region:'Exploration', statement:"Ezreal est principalement connu comme roi du Freljord.", correct:false, explanation:"Ezreal est avant tout un explorateur, connu pour ses expéditions dans des ruines anciennes."},
{id:'vf-017', region:'Noxus / Zaun', statement:"Urgot a été trahi par Noxus et jeté dans les égouts de Zaun.", correct:true, explanation:"Ancien exécuteur de Noxus, Urgot fut trahi par l'empire qu'il servait."},
{id:'vf-018', region:'Demacia', statement:"Xin Zhao est le garde du corps du prince Jarvan IV.", correct:true, explanation:"Xin Zhao a juré fidélité au prince Jarvan IV et veille sur sa sécurité."},
{id:'vf-019', region:'Royaume des morts', statement:"Mordekaiser règne sur un royaume paisible de vivants.", correct:false, explanation:"Mordekaiser domine un royaume des morts, qu'il contrôle par la force."},
{id:'vf-020', region:'Ionia', statement:"Wukong pratique l'art du bâton, une tradition originaire d'Ionia.", correct:true, explanation:"Wukong manie le bâton avec l'agilité propre aux arts martiaux ioniens."},
{id:'vf-021', region:'Îles Obscures', statement:"Viego est connu sous le nom du Roi-Brisé et règne sur les Îles Obscures.", correct:true, explanation:"Consumé par le chagrin, Viego hante et domine les Îles Obscures."},
{id:'vf-022', region:'Îles Obscures', statement:"Le Harrowing est un événement où les frontières avec les Îles Obscures s'affaiblissent.", correct:true, explanation:"Durant le Harrowing, le voile entre les vivants et les Îles Obscures s'amincit dangereusement."},
{id:'vf-023', region:'Demacia', statement:"Sylas est un noble démacien célébré pour sa loyauté à la couronne.", correct:false, explanation:"Sylas a au contraire été emprisonné par Demacia pour son don magique interdit."},
{id:'vf-024', region:'Ixtal', statement:"Qiyana est une princesse d'Ixtal.", correct:true, explanation:"Qiyana est l'héritière d'un clan élémentaire de la région isolée d'Ixtal."},
{id:'vf-025', region:'Bilgewater', statement:"Illaoi est prêtresse du dieu-krak Nagakabouros.", correct:true, explanation:"Illaoi sert Nagakabouros, divinité marine vénérée à Bilgewater."},
{id:'vf-026', region:'Piltover / Zaun', statement:"Viktor souhaite fusionner l'homme et la machine, un idéal qu'il nomme la Gloire Évolutive.", correct:true, explanation:"Viktor considère la fusion entre chair et machine comme la seule voie vers un progrès véritable."},
{id:'vf-027', region:'Le Néant', statement:"Kai'Sa a survécu de nombreuses années dans le Néant.", correct:true, explanation:"Cette survie prolongée a fusionné son corps avec une armure vivante issue du Néant."},
{id:'vf-028', region:'Shurima', statement:"Nasus et Renekton sont des frères originaires de Shurima.", correct:true, explanation:"Ces deux gardiens ascendus sont liés à l'antique empire de Shurima."},
{id:'vf-029', region:'Piltover / Zaun', statement:"Jayce est reconnu comme le créateur du marteau hextech.", correct:true, explanation:"Jayce a conçu une arme hextech transformable devenue emblématique de Piltover."},
{id:'vf-030', region:'Vastaya', statement:"Les Vastaya, comme Ahri ou Rakan, sont entièrement mécaniques.", correct:false, explanation:"Les Vastaya sont des créatures mi-humaines, mi-animales, liées à une magie ancienne — pas des machines."}
];
